### ISSUE TITLE
Enable/Fix View Log, and add log verbosity settings.

### ISSUE THREAD

**Issue by d7an** [GetOvert/Overt#42]
Overt: 0.5.7, macOS: 13.2.1

Click on TASKS  -> VIEW LOG, you get a list of brew command actions to be performed on the left and a big black log viewing console area.  However in most cases, there's no log displayed, which is kinda weird, give the user the impression something is not working.

1. Please enable the ability to display logs for each brew command, even when there's no error
2. Add ability to set log verbosity, i.e. passing -v or -d to brew command

**Comment by ThatsJustCheesy** [comment]
(2) is a nice idea.

For (1), it's a bit tricky because a lot of the data gathering commands are run **concurrently** in the background, for performance reasons. The best I could do with the existing Log view is to tack on the output from background commands once they have finished completely (to prevent misleading/unreadable interleaved output).

I will consider doing (1), but at the very least, you've raised an important UX point, so I'll make sure to add a note at the beginning of the log that makes it clearer what actually gets logged.

(Also, it isn't a _good_ solution, but if any background commands fail, their output gets logged to the devtools console; press press ⌥⌘I (letter eye))

**Comment by ThatsJustCheesy** [comment]
For (2), I've added the setting:

<img width="430" alt="Screen Shot 2023-04-10 at 11 45 13 PM" src="https://user-images.githubusercontent.com/16456186/231050847-aa347a0e-9d8a-49e5-a25f-88bab65ded57.png">

For (1), I've added this explanatory message to the top of the Log view:

<img width="1104" alt="Screen Shot 2023-04-10 at 11 45 21 PM" src="https://user-images.githubusercontent.com/16456186/231050892-8d374a17-2809-4849-8443-f068deed6b5d.png">
